export const cars = [
  {
    name: "Chevrolet Malibu",
    trim: "LT",
    generation: "Eighth",
    year: 2022,
    color: "#4682B4",
    colorName: "Polat ko'k",
    category: "Sedan",
    doorCount: 4,
    seatCount: 5,
    maxSpeed: "210 km/h",
    acceleration: "0-100 km/h: 8.6s",
    engine: "1.5L Turbo I4",
    horsepower: 160,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "9.2 L/100km",
      highway: "6.7 L/100km",
      combined: "8.1 L/100km",
    },
    country: "AQSH",
    description: "Qulay va tejamkor o'rta o'lchamli sedan",
    id: 1,
  },
  {
    name: "Toyota Camry",
    trim: "XLE",
    generation: "Sakkizinchi",
    year: 2023,
    color: "#000000",
    colorName: "Qora",
    category: "Sedan",
    doorCount: 4,
    seatCount: 5,
    maxSpeed: "180 km/h",
    acceleration: "0-100 km/h: 8.2s",
    engine: "2.5L Hybrid",
    horsepower: 208,
    fuelType: "Gibrid",
    fuelConsumption: {
      city: "4.5 L/100km",
      highway: "5.0 L/100km",
      combined: "4.7 L/100km",
    },
    country: "Yaponiya",
    description: "Ishonchli va tejamkor gibrid sedan",
    id: 2,
  },
  {
    name: "BMW X5",
    trim: "xDrive40i",
    generation: "To'rtinchi",
    year: 2023,
    color: "#C0C0C0",
    colorName: "Kumush",
    category: "SUV",
    doorCount: 5,
    seatCount: 7,
    maxSpeed: "243 km/h",
    acceleration: "0-100 km/h: 5.5s",
    engine: "3.0L Turbo I6",
    horsepower: 335,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "11.7 L/100km",
      highway: "8.7 L/100km",
      combined: "10.4 L/100km",
    },
    country: "Germaniya",
    description: "Lyuks va kuchli oliy sinf SUV",
    id: 3,
  },
  {
    name: "Mercedes-Benz C-Class",
    trim: "AMG Line",
    generation: "Beshinchi",
    year: 2022,
    color: "#FFD700",
    colorName: "Oltin",
    category: "Sedan",
    doorCount: 4,
    seatCount: 5,
    maxSpeed: "250 km/h",
    acceleration: "0-100 km/h: 6.0s",
    engine: "2.0L Turbo I4",
    horsepower: 255,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "9.1 L/100km",
      highway: "6.3 L/100km",
      combined: "7.5 L/100km",
    },
    country: "Germaniya",
    description: "Elegant va zamonaviy premium sedan",
    id: 4,
  },
  {
    name: "Hyundai Tucson",
    trim: "Premium",
    generation: "To'rtinchi",
    year: 2023,
    color: "#FF6347",
    colorName: "Baliq qizil",
    category: "SUV",
    doorCount: 5,
    seatCount: 5,
    maxSpeed: "190 km/h",
    acceleration: "0-100 km/h: 9.5s",
    engine: "2.5L MPI",
    horsepower: 180,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "10.2 L/100km",
      highway: "7.6 L/100km",
      combined: "9.0 L/100km",
    },
    country: "Koreya",
    description: "Zamonaviy dizaynga ega oilaviy SUV",
    id: 5,
  },
  {
    name: "Kia Sportage",
    trim: "GT-Line",
    generation: "Beshinchi",
    year: 2023,
    color: "#000080",
    colorName: "Dengiz ko'k",
    category: "SUV",
    doorCount: 5,
    seatCount: 5,
    maxSpeed: "195 km/h",
    acceleration: "0-100 km/h: 8.8s",
    engine: "1.6L Turbo",
    horsepower: 180,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "9.8 L/100km",
      highway: "7.2 L/100km",
      combined: "8.6 L/100km",
    },
    country: "Koreya",
    description: "Sport ko'rinishli va qulay SUV",
    id: 6,
  },
  {
    name: "Ford Mustang",
    trim: "GT",
    generation: "Oltinchi",
    year: 2022,
    color: "#FF0000",
    colorName: "Qizil",
    category: "Kupe",
    doorCount: 2,
    seatCount: 4,
    maxSpeed: "250 km/h",
    acceleration: "0-100 km/h: 4.3s",
    engine: "5.0L V8",
    horsepower: 450,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "15.7 L/100km",
      highway: "9.8 L/100km",
      combined: "12.8 L/100km",
    },
    country: "AQSH",
    description: "Afsonaviy Amerika sport kupe",
    id: 7,
  },
  {
    name: "Tesla Model 3",
    trim: "Long Range",
    generation: "Birinchi",
    year: 2023,
    color: "#FFFFFF",
    colorName: "Oq",
    category: "Sedan",
    doorCount: 4,
    seatCount: 5,
    maxSpeed: "233 km/h",
    acceleration: "0-100 km/h: 4.4s",
    engine: "Elektromotor",
    horsepower: 346,
    fuelType: "Elektrik",
    fuelConsumption: {
      city: "15.5 kWh/100km",
      highway: "16.5 kWh/100km",
      combined: "16.0 kWh/100km",
    },
    country: "AQSH",
    description: "Zamonaviy va tezkor elektromobil",
    id: 8,
  },
  {
    name: "Nissan Qashqai",
    trim: "Tekna",
    generation: "Uchinchi",
    year: 2022,
    color: "#808080",
    colorName: "Kulrang",
    category: "Krossover",
    doorCount: 5,
    seatCount: 5,
    maxSpeed: "190 km/h",
    acceleration: "0-100 km/h: 9.9s",
    engine: "1.3L Turbo",
    horsepower: 140,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "8.2 L/100km",
      highway: "6.0 L/100km",
      combined: "7.0 L/100km",
    },
    country: "Yaponiya",
    description: "Ishonchli va amaliy krossover",
    id: 9,
  },
  {
    name: "Volkswagen Tiguan",
    trim: "R-Line",
    generation: "Ikkinchi",
    year: 2023,
    color: "#8B4513",
    colorName: "Jigarrang",
    category: "SUV",
    doorCount: 5,
    seatCount: 5,
    maxSpeed: "200 km/h",
    acceleration: "0-100 km/h: 8.5s",
    engine: "2.0L TSI",
    horsepower: 190,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "10.5 L/100km",
      highway: "7.8 L/100km",
      combined: "9.0 L/100km",
    },
    country: "Germaniya",
    description: "Oila uchun mos keladigan nemis SUV",
    id: 10,
  },
  {
    name: "Audi A6",
    trim: "S-Line",
    generation: "Beshinchi",
    year: 2022,
    color: "#2F4F4F",
    colorName: "To'q kulrang",
    category: "Sedan",
    doorCount: 4,
    seatCount: 5,
    maxSpeed: "250 km/h",
    acceleration: "0-100 km/h: 5.8s",
    engine: "3.0L V6",
    horsepower: 340,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "11.2 L/100km",
      highway: "7.1 L/100km",
      combined: "8.8 L/100km",
    },
    country: "Germaniya",
    description: "Biznes-klass premium sedan",
    id: 11,
  },
  {
    name: "Lexus RX",
    trim: "F-Sport",
    generation: "To'rtinchi",
    year: 2023,
    color: "#4B0082",
    colorName: "Binafsha",
    category: "SUV",
    doorCount: 5,
    seatCount: 5,
    maxSpeed: "230 km/h",
    acceleration: "0-100 km/h: 7.7s",
    engine: "3.5L V6",
    horsepower: 295,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "11.8 L/100km",
      highway: "8.5 L/100km",
      combined: "10.3 L/100km",
    },
    country: "Yaponiya",
    description: "Lyuks va ishonchli premium SUV",
    id: 12,
  },
  {
    name: "Honda Civic",
    trim: "Sport",
    generation: "O'n birinchi",
    year: 2022,
    color: "#00FF00",
    colorName: "Yashil",
    category: "Sedan",
    doorCount: 4,
    seatCount: 5,
    maxSpeed: "200 km/h",
    acceleration: "0-100 km/h: 8.5s",
    engine: "2.0L i-VTEC",
    horsepower: 158,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "8.7 L/100km",
      highway: "6.4 L/100km",
      combined: "7.6 L/100km",
    },
    country: "Yaponiya",
    description: "Ishonchli va tejamkor kompakt sedan",
    id: 13,
  },
  {
    name: "Porsche 911",
    trim: "Carrera S",
    generation: "Sakkizinchi",
    year: 2023,
    color: "#FF8C00",
    colorName: "To'q sariq",
    category: "Kupe",
    doorCount: 2,
    seatCount: 4,
    maxSpeed: "308 km/h",
    acceleration: "0-100 km/h: 3.7s",
    engine: "3.0L Twin-Turbo",
    horsepower: 450,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "12.5 L/100km",
      highway: "8.9 L/100km",
      combined: "10.4 L/100km",
    },
    country: "Germaniya",
    description: "Afsonaviy sport kupe",
    id: 14,
  },
  {
    name: "Mazda CX-5",
    trim: "Skyactiv-G",
    generation: "Ikkinchi",
    year: 2022,
    color: "#E6E6FA",
    colorName: "Lavanta",
    category: "SUV",
    doorCount: 5,
    seatCount: 5,
    maxSpeed: "195 km/h",
    acceleration: "0-100 km/h: 9.2s",
    engine: "2.0L Skyactiv-G",
    horsepower: 165,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "9.0 L/100km",
      highway: "6.8 L/100km",
      combined: "8.0 L/100km",
    },
    country: "Yaponiya",
    description: "Yaxshi dizaynga ega krossover",
    id: 15,
  },
  {
    name: "Volvo XC90",
    trim: "Inscription",
    generation: "Ikkinchi",
    year: 2023,
    color: "#F5F5DC",
    colorName: "Bej",
    category: "SUV",
    doorCount: 5,
    seatCount: 7,
    maxSpeed: "210 km/h",
    acceleration: "0-100 km/h: 6.5s",
    engine: "2.0L Twin-Charger",
    horsepower: 310,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "11.2 L/100km",
      highway: "8.5 L/100km",
      combined: "9.8 L/100km",
    },
    country: "Shvetsiya",
    description: "Xavfsiz va qulay lyuks SUV",
    id: 16,
  },
  {
    name: "Subaru Outback",
    trim: "Touring",
    generation: "Oltinchi",
    year: 2022,
    color: "#A52A2A",
    colorName: "Jigarrang",
    category: "Universal",
    doorCount: 5,
    seatCount: 5,
    maxSpeed: "190 km/h",
    acceleration: "0-100 km/h: 8.5s",
    engine: "2.5L Boxer",
    horsepower: 182,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "9.8 L/100km",
      highway: "7.4 L/100km",
      combined: "8.7 L/100km",
    },
    country: "Yaponiya",
    description: "Hamma yo'lga mos universal",
    id: 17,
  },
  {
    name: "Jeep Wrangler",
    trim: "Rubicon",
    generation: "JL",
    year: 2023,
    color: "#008000",
    colorName: "Yashil",
    category: "Off-road",
    doorCount: 4,
    seatCount: 5,
    maxSpeed: "180 km/h",
    acceleration: "0-100 km/h: 8.4s",
    engine: "3.6L V6",
    horsepower: 285,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "13.8 L/100km",
      highway: "10.2 L/100km",
      combined: "12.1 L/100km",
    },
    country: "AQSH",
    description: "Haqiqiy off-road yo'l qo'riqchisi",
    id: 18,
  },
  {
    name: "Land Rover Defender",
    trim: "X-Dynamic",
    generation: "Ikkinchi",
    year: 2022,
    color: "#556B2F",
    colorName: "Zaytun",
    category: "Off-road",
    doorCount: 5,
    seatCount: 7,
    maxSpeed: "200 km/h",
    acceleration: "0-100 km/h: 7.1s",
    engine: "3.0L Turbo",
    horsepower: 400,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "14.2 L/100km",
      highway: "10.1 L/100km",
      combined: "12.2 L/100km",
    },
    country: "Buyuk Britaniya",
    description: "Zamonaviy va qiyinchiliklardan qo'rqmaydigan off-road",
    id: 19,
  },
  {
    name: "Skoda Octavia",
    trim: "Style",
    generation: "To'rtinchi",
    year: 2023,
    color: "#FFC0CB",
    colorName: "Pushti",
    category: "Universal",
    doorCount: 5,
    seatCount: 5,
    maxSpeed: "220 km/h",
    acceleration: "0-100 km/h: 8.0s",
    engine: "2.0L TSI",
    horsepower: 190,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "9.2 L/100km",
      highway: "6.5 L/100km",
      combined: "7.6 L/100km",
    },
    country: "Chexiya",
    description: "Keng va amaliy universal",
    id: 20,
  },
  {
    name: "Renault Duster",
    trim: "Expression",
    generation: "Ikkinchi",
    year: 2022,
    color: "#FFFF00",
    colorName: "Sariq",
    category: "SUV",
    doorCount: 5,
    seatCount: 5,
    maxSpeed: "175 km/h",
    acceleration: "0-100 km/h: 11.5s",
    engine: "1.6L MPI",
    horsepower: 114,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "9.5 L/100km",
      highway: "6.8 L/100km",
      combined: "8.0 L/100km",
    },
    country: "Fransiya",
    description: "Iqtisodiy va ishonchli SUV",
    id: 21,
  },
  {
    name: "Chevrolet Tahoe",
    trim: "LTZ",
    generation: "To'rtinchi",
    year: 2023,
    color: "#800020",
    colorName: "Bordo",
    category: "SUV",
    doorCount: 5,
    seatCount: 8,
    maxSpeed: "190 km/h",
    acceleration: "0-100 km/h: 7.1s",
    engine: "5.3L V8",
    horsepower: 355,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "16.8 L/100km",
      highway: "11.2 L/100km",
      combined: "14.2 L/100km",
    },
    country: "AQSH",
    description: "Katta oila uchun keng SUV",
    id: 22,
  },
  {
    name: "Toyota RAV4",
    trim: "Adventure",
    generation: "Beshinchi",
    year: 2022,
    color: "#00FFFF",
    colorName: "Moviy",
    category: "SUV",
    doorCount: 5,
    seatCount: 5,
    maxSpeed: "180 km/h",
    acceleration: "0-100 km/h 8.6s",
    engine: "2.5L Dynamic Force",
    horsepower: 203,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "8.7 L/100km",
      highway: "6.9 L/100km",
      combined: "7.8 L/100km",
    },
    country: "Yaponiya",
    description: "Dunyoda eng mashhur krossover",
    id: 23,
  },
  {
    name: "BMW 5 Series",
    trim: "M Sport",
    generation: "Yettinchi",
    year: 2023,
    color: "#000000",
    colorName: "Qora",
    category: "Sedan",
    doorCount: 4,
    seatCount: 5,
    maxSpeed: "250 km/h",
    acceleration: "0-100 km/h: 5.9s",
    engine: "3.0L Turbo",
    horsepower: 335,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "11.3 L/100km",
      highway: "7.2 L/100km",
      combined: "8.9 L/100km",
    },
    country: "Germaniya",
    description: "Biznes klassning nemis standarti",
    id: 24,
  },
  {
    name: "Mercedes GLE",
    trim: "AMG Line",
    generation: "Uchinchi",
    year: 2022,
    color: "#C0C0C0",
    colorName: "Kumush",
    category: "SUV",
    doorCount: 5,
    seatCount: 5,
    maxSpeed: "240 km/h",
    acceleration: "0-100 km/h: 6.0s",
    engine: "3.0L Turbo",
    horsepower: 367,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "12.1 L/100km",
      highway: "8.9 L/100km",
      combined: "10.4 L/100km",
    },
    country: "Germaniya",
    description: "Lyuks va kuchli premium SUV",
    id: 25,
  },
  {
    name: "Hyundai Sonata",
    trim: "N-Line",
    generation: "Sakkizinchi",
    year: 2023,
    color: "#FF4500",
    colorName: "Qizil-orange",
    category: "Sedan",
    doorCount: 4,
    seatCount: 5,
    maxSpeed: "240 km/h",
    acceleration: "0-100 km/h: 6.5s",
    engine: "2.5L Turbo",
    horsepower: 290,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "11.2 L/100km",
      highway: "7.8 L/100km",
      combined: "9.5 L/100km",
    },
    country: "Koreya",
    description: "Sport ko'rinishli o'rta o'lchamli sedan",
    id: 26,
  },
  {
    name: "Kia K5",
    trim: "GT",
    generation: "Birinchi",
    year: 2022,
    color: "#000080",
    colorName: "To'q ko'k",
    category: "Sedan",
    doorCount: 4,
    seatCount: 5,
    maxSpeed: "240 km/h",
    acceleration: "0-100 km/h: 6.6s",
    engine: "2.5L Turbo",
    horsepower: 290,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "11.0 L/100km",
      highway: "7.6 L/100km",
      combined: "9.3 L/100km",
    },
    country: "Koreya",
    description: "Dinamik va zamonaviy biznes sedan",
    id: 27,
  },
  {
    name: "Ford F-150",
    trim: "Raptor",
    generation: "O'n uchinchi",
    year: 2023,
    color: "#964B00",
    colorName: "Jigarrang",
    category: "Pikap",
    doorCount: 4,
    seatCount: 5,
    maxSpeed: "190 km/h",
    acceleration: "0-100 km/h: 5.7s",
    engine: "3.5L Twin-Turbo",
    horsepower: 450,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "16.8 L/100km",
      highway: "13.1 L/100km",
      combined: "15.1 L/100km",
    },
    country: "AQSH",
    description: "Dunyoning eng mashhur pikapi",
    id: 28,
  },
  {
    name: "Tesla Model Y",
    trim: "Performance",
    generation: "Birinchi",
    year: 2022,
    color: "#808080",
    colorName: "Kulrang",
    category: "SUV",
    doorCount: 5,
    seatCount: 7,
    maxSpeed: "250 km/h",
    acceleration: "0-100 km/h: 3.7s",
    engine: "Ikki motorli",
    horsepower: 456,
    fuelType: "Elektrik",
    fuelConsumption: {
      city: "16.8 kWh/100km",
      highway: "18.2 kWh/100km",
      combined: "17.5 kWh/100km",
    },
    country: "AQSH",
    description: "Tezkor va zamonaviy elektrik SUV",
    id: 29,
  },
  {
    name: "Nissan X-Trail",
    trim: "Tekna",
    generation: "To'rtinchi",
    year: 2023,
    color: "#E6E6FA",
    colorName: "Lavanta",
    category: "SUV",
    doorCount: 5,
    seatCount: 7,
    maxSpeed: "190 km/h",
    acceleration: "0-100 km/h: 9.5s",
    engine: "1.5L Turbo",
    horsepower: 163,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "8.9 L/100km",
      highway: "6.7 L/100km",
      combined: "7.8 L/100km",
    },
    country: "Yaponiya",
    description: "Oila uchun mos keladigan krossover",
    id: 30,
  },
  {
    name: "Volkswagen Passat",
    trim: "R-Line",
    generation: "Sakkizinchi",
    year: 2022,
    color: "#2F4F4F",
    colorName: "To'q kulrang",
    category: "Universal",
    doorCount: 5,
    seatCount: 5,
    maxSpeed: "240 km/h",
    acceleration: "0-100 km/h: 7.6s",
    engine: "2.0L TSI",
    horsepower: 280,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "10.2 L/100km",
      highway: "7.1 L/100km",
      combined: "8.4 L/100km",
    },
    country: "Germaniya",
    description: "Klassik nemis universal",
    id: 31,
  },
  {
    name: "Audi Q7",
    trim: "S-Line",
    generation: "Ikkinchi",
    year: 2023,
    color: "#000000",
    colorName: "Qora",
    category: "SUV",
    doorCount: 5,
    seatCount: 7,
    maxSpeed: "250 km/h",
    acceleration: "0-100 km/h: 5.9s",
    engine: "3.0L TFSI",
    horsepower: 340,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "12.5 L/100km",
      highway: "8.9 L/100km",
      combined: "10.5 L/100km",
    },
    country: "Germaniya",
    description: "Keng va lyuks premium SUV",
    id: 32,
  },
  {
    name: "Lexus ES",
    trim: "Luxury",
    generation: "Yettinchi",
    year: 2022,
    color: "#FFFFFF",
    colorName: "Oq",
    category: "Sedan",
    doorCount: 4,
    seatCount: 5,
    maxSpeed: "210 km/h",
    acceleration: "0-100 km/h: 8.6s",
    engine: "3.5L V6",
    horsepower: 302,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "11.2 L/100km",
      highway: "7.8 L/100km",
      combined: "9.6 L/100km",
    },
    country: "Yaponiya",
    description: "Qulay va sokin premium sedan",
    id: 33,
  },
  {
    name: "Honda CR-V",
    trim: "Executive",
    generation: "Beshinchi",
    year: 2023,
    color: "#FFA500",
    colorName: "Orange",
    category: "SUV",
    doorCount: 5,
    seatCount: 5,
    maxSpeed: "190 km/h",
    acceleration: "0-100 km/h: 9.3s",
    engine: "1.5L Turbo",
    horsepower: 190,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "9.2 L/100km",
      highway: "7.0 L/100km",
      combined: "8.1 L/100km",
    },
    country: "Yaponiya",
    description: "Ishonchli va amaliy krossover",
    id: 34,
  },
  {
    name: "Porsche Cayenne",
    trim: "S",
    generation: "Uchinchi",
    year: 2022,
    color: "#800000",
    colorName: "To'q qizil",
    category: "SUV",
    doorCount: 5,
    seatCount: 5,
    maxSpeed: "265 km/h",
    acceleration: "0-100 km/h: 5.0s",
    engine: "2.9L Twin-Turbo",
    horsepower: 440,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "13.2 L/100km",
      highway: "9.5 L/100km",
      combined: "11.1 L/100km",
    },
    country: "Germaniya",
    description: "Sport va lyuks SUV",
    id: 35,
  },
  {
    name: "Mazda 6",
    trim: "Takumi",
    generation: "Uchinchi",
    year: 2023,
    color: "#4682B4",
    colorName: "Polat ko'k",
    category: "Sedan",
    doorCount: 4,
    seatCount: 5,
    maxSpeed: "220 km/h",
    acceleration: "0-100 km/h: 7.8s",
    engine: "2.5L Turbo",
    horsepower: 250,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "10.5 L/100km",
      highway: "7.5 L/100km",
      combined: "8.9 L/100km",
    },
    country: "Yaponiya",
    description: "Elegant va dinamik biznes sedan",
    id: 36,
  },
  {
    name: "Volvo S90",
    trim: "Inscription",
    generation: "Ikkinchi",
    year: 2022,
    color: "#F5F5F5",
    colorName: "Oq",
    category: "Sedan",
    doorCount: 4,
    seatCount: 5,
    maxSpeed: "230 km/h",
    acceleration: "0-100 km/h: 6.8s",
    engine: "2.0L Twin-Charger",
    horsepower: 310,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "10.8 L/100km",
      highway: "7.6 L/100km",
      combined: "9.0 L/100km",
    },
    country: "Shvetsiya",
    description: "Skandinaviya uslubidagi lyuks sedan",
    id: 37,
  },
  {
    name: "Cadillac Escalade-V",
    trim: "V-Series",
    generation: "Fifth",
    year: 2023,
    color: "#2F4F4F",
    colorName: "Dark Slate",
    category: "SUV",
    doorCount: 4,
    seatCount: 7,
    maxSpeed: "200 km/h",
    acceleration: "0-100 km/h: 4.4s",
    engine: "6.2L Supercharged V8",
    horsepower: 682,
    fuelType: "Benzin",
    fuelConsumption: {
      city: "19.6 L/100km",
      highway: "12.4 L/100km",
      combined: "15.2 L/100km",
    },
    country: "AQSH",
    description: "Kuchli superzaryadlangan dvigatel va yakuniy lyuks",
    id: 38,
  },
];
